name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: SSH-Compose
      uses: matiasnu/github-action-ssh-docker-compose@v2.0.1

      with:
        ssh_host: 158.160.55.139
        ssh_private_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
        ssh_user: ${{ secrets.DEPLOY_SSH_USER }}
        docker_compose_prefix: team_01
