name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: create env file
      run: |
        touch .env
        echo CLIENT_PORT=${{ secrets.CLIENT_PORT }} >> .env &&
        echo SERVER_PORT=${{ secrets.SERVER_PORT }} >> .env &&
        echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env &&
        echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env &&
        echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env &&
        echo POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} >> .env &&
        echo PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL }} >> .env &&
        echo PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD }} >> .env &&
        echo PGADMIN_LISTEN_PORT=${{ secrets.PGADMIN_LISTEN_PORT }} >> .env
    
    - name: create cert.pem file
      env:
        CERT: ${{ secrets.CERT_PEM }}
      run: |
        mkdir keys
        touch keys/cert.pem
        echo "$CERT" > keys/cert.pem
    
    - name: create key.pem file
      env:
        KEY_PEM: ${{ secrets.KEY_PEM }}
      run: |
        touch keys/key.pem
        echo "$KEY_PEM" > keys/key.pem
        
    - name: create keytmp.pem file
      env:
        KEYTMP: ${{ secrets.KEYTMP_PEM }}
      run: |
        touch keys/keytmp.pem
        echo "$KEYTMP" > keys/keytmp.pem
        
    - name: create client env file
      run: |
        ls -la
        touch packages/client/.env
        echo ${{ secrets.ENV_CLIENT }} >> packages/client/.env
    
    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment

      with:
        ssh_host: 158.160.55.139
        ssh_private_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
        ssh_user: ${{ secrets.DEPLOY_COM_SSH_USER }}
        docker_compose_prefix: team_01
        docker_compose_filename: docker-compose.yml
